"use strict";
exports.SWITCH_ARTICLE_CATEGORY = "SWITCH_ARTICLE_CATEGORY";
exports.FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
exports.FETCHING_ARTICLE_LIST = "FETCHING_ARTICLE_LIST";
exports.FETCH_COMMENT_LIST = "FETCH_COMMENT_LIST";
exports.RESET_COMMENT_LIST = "RESET_COMMENT_LIST";
exports.FETCH_USER_INFO = "FETCH_USER_INFO";
