"use strict";

export const SWITCH_ARTICLE_CATEGORY = "SWITCH_ARTICLE_CATEGORY";

export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";

export const FETCHING_ARTICLE_LIST = "FETCHING_ARTICLE_LIST";

export const FETCH_COMMENT_LIST = "FETCH_COMMENT_LIST";

export const RESET_COMMENT_LIST = "RESET_COMMENT_LIST";

export const FETCH_USER_INFO = "FETCH_USER_INFO";